version: '3.7'

networks:
  backend_nw:
    driver: bridge

volumes:
  db_data: {}

services:

  nginx:
    container_name: nginx
    image: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend_nw
    ports:
      - 8099:8080
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - db
      - pgweb
      - user_service

  user_service:
    build:
      context: ./user_service/
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${US_DB_NAME:-users_bank}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-P@ssw0rd}
    networks:
      - backend_nw
    depends_on:
      - db
      - pgweb

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-P@ssw0rd}
    networks:
      - backend_nw
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: always
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-P@ssw0rd}@db:5432/postgres?sslmode=disable
    ports:
      - 8083:8081
    networks:
      - backend_nw
