openapi: 3.0.1
info:
  title: User service
  description: Сервис пользователей
  version: 0.0.1
servers:
  - url: /api
    description: Main api
paths:
  /ping:
    get:
      operationId: user_service.api.handlers.status.ping
      tags:
        - ping
      summary: ping
      responses:
        401:
          description: Unauthorized
        400:
          description: Bad Request
        200:
          description: Ok
  /status:
    post:
      operationId: user_service.api.handlers.user.get_user
      tags:
        - getUser
      summary: getUser
      requestBody:
        description: 'Get user'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getUser'
      responses:
        401:
          description: Unauthorized
        400:
          description: Bad Request
        200:
          description: Ok

  /create_user:
    post:
      operationId: user_service.api.handlers.user.create_user
      tags:
        - createusr
      summary: createusr
      requestBody:
        description: 'test'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUsers'
      responses:
        401:
          description: Unauthorized
        400:
          description: Bad Request
        200:
          description: Ok
  /add:
    put:
      operationId: user_service.api.handlers.user.add
      tags:
        - balanceReplenishment
      summary: balance replenishment
      requestBody:
        description: 'Пополнение баланса пользователя'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add'
      responses:
        401:
          description: Unauthorized
        400:
          description: Bad Request
        200:
          description: Ok

  /subtract:
    put:
      operationId: user_service.api.handlers.user.subtract
      tags:
        - balanceSubtract
      summary: balance subtract
      requestBody:
        description: 'Вычитание баланса пользователя'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subtract'
      responses:
        401:
          description: Unauthorized
        400:
          description: Bad Request
        200:
          description: Ok

components:
  schemas:

    createUsers:
      type: object
      required: ["fio","current_balans"]
      properties:
        fio:
          type: string
        current_balans:
          type: integer
        hold:
          type: integer
        status:
          type: boolean

    getUser:
      type: object
      required: ["uuid"]
      properties:
        uuid:
          type: string

    add:
      type: object
      required: ['uuid', 'added']
      properties:
        uuid:
          type: string
        added:
          type: integer

    subtract:
      type: object
      required: ['uuid', 'subtract']
      properties:
        uuid:
          type: string
        subtract:
          type: integer


